### ISSUE TITLE
Unable to use UserDefaults to show lists

### ISSUE THREAD

**Issue by khainl1110** [TaskAppHehe/FirstVersion#1]
Using SwiftUI, I have trouble using UserDefaults so that whenever user add a new item, it will appear on the task list. I will put the task list and add new task at the same screen so that I don't need to use UserDefaults to communicate between them.

**Comment by Daphne-CPAdmin** [comment]
Missing Updated README with Schema Section:

- Data Models (3pts)
- Networking (2pts)
